# Generated by Django 4.2.4 on 2023-09-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='shot_info',
            new_name='short_info',
        ),
    ]
